#!/bin/bash

rsync -rav --delete -e 'ssh -i ./.scaleway' \
	--exclude '.*' \
	--exclude node_modules \
	--exclude data \
	--exclude documents \
	. root@didb.jannisr.de:~/didb/

ssh -i ./.scaleway root@didb.jannisr.de "\
cd ~/didb
npm i
export NODE_ENV=production
npm run stop-frontend
npm run start-frontend
npm run stop-backend
npm run start-backend"
